### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by SKTBoom** [may1as/UsbKeyboardDataexp#1]
Traceback (most recent call last):
  File "/UsbKbCracker/UsbKbCracker.py", line 156, in <module>
    kbparser.tshark_do(pcapfile=arg.pcapfile, fieldvalue=arg.fieldvalue, filterfield=arg.filterfield)
  File "/UsbKbCracker/UsbKbCracker.py", line 35, in tshark_do
    if filterfield not in None:
TypeError: argument of type 'NoneType' is not iterable

**Comment by P001water** [comment]
已经在题目中用过许多次了 没有遇见问题。如果题目类型变了，注意自行灵活修改脚本
